name: Issue Auto Comment

on:
  issues:
    types: [opened]

jobs:
  issue-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Add Issue Comment
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue = context.payload.issue;

            // 이슈 라벨에 따른 맞춤 응답
            const labels = issue.labels.map(label => label.name);

            let welcomeMessage = `
            ## 👋 새로운 이슈가 생성되었습니다!

            안녕하세요 @${issue.user.login}님! 이슈를 생성해주셔서 감사합니다.
            `;

            // 이슈 타입별 맞춤 메시지
            if (labels.includes('bug')) {
              welcomeMessage += `

            ### 🐛 버그 리포트 확인사항

            버그 리포트를 작성해주셔서 감사합니다. 빠른 해결을 위해 다음 정보가 포함되었는지 확인해주세요:

            - [ ] **재현 단계**: 버그를 재현할 수 있는 명확한 단계
            - [ ] **예상 결과**: 어떤 결과를 예상했는지
            - [ ] **실제 결과**: 실제로 어떤 일이 발생했는지  
            - [ ] **환경 정보**: OS, 브라우저, 버전 정보 등
            - [ ] **스크린샷**: 가능하다면 문제 상황의 스크린샷

            누락된 정보가 있다면 추가로 제공해주시면 더 빠르게 도움을 드릴 수 있습니다.
              `;
            } else if (labels.includes('enhancement') || labels.includes('feature')) {
              welcomeMessage += `

            ### ✨ 기능 요청 확인사항

            새로운 기능 아이디어를 제안해주셔서 감사합니다! 다음 사항들이 포함되었는지 확인해주세요:

            - [ ] **기능 설명**: 원하는 기능에 대한 명확한 설명
            - [ ] **사용 사례**: 이 기능이 어떤 상황에서 유용한지
            - [ ] **예상 동작**: 기능이 어떻게 작동해야 하는지
            - [ ] **대안 고려**: 다른 해결방법을 고려해보셨는지

            제안해주신 기능을 검토한 후 구현 계획을 공유드리겠습니다.
              `;
            } else if (labels.includes('question')) {
              welcomeMessage += `

            ### ❓ 질문에 대한 안내

            질문해주셔서 감사합니다! 더 정확한 답변을 위해 다음 사항을 확인해주세요:

            - [ ] **명확한 질문**: 궁금한 점을 구체적으로 설명
            - [ ] **시도한 방법**: 이미 시도해본 해결방법이 있는지
            - [ ] **관련 코드**: 질문과 관련된 코드나 설정이 있는지
            - [ ] **참고 문서**: 관련 문서를 확인해보셨는지

            가능한 한 빠르게 답변드리도록 하겠습니다.
              `;
            } else {
              welcomeMessage += `

            ### 📋 일반 이슈 처리 안내

            이슈를 검토한 후 적절한 라벨을 추가하고 담당자를 할당하겠습니다.

            - 긴급한 문제의 경우 'priority-critical' 라벨을 추가해주세요
            - 관련 문서나 참고자료가 있다면 링크를 추가해주세요
            - 추가 정보가 필요할 경우 코멘트로 요청드리겠습니다
              `;
            }

            welcomeMessage += `

            ### 📞 추가 도움이 필요하시면

            - 📚 [프로젝트 문서](docs/) 확인
            - 🔍 기존 이슈 검색으로 중복 확인  
            - 💬 추가 질문이나 정보 제공은 이 이슈에 코멘트로 남겨주세요

            ---
            *담당자가 곧 이슈를 검토하고 응답드리겠습니다. 감사합니다! 🙏*
            `;

            // 댓글 작성
            try {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: issue.number,
                body: welcomeMessage
              });
              
              console.log('Auto issue comment added');
            } catch (error) {
              console.log(`Error adding issue comment: ${error.message}`);
            }
